### ISSUE TITLE
gtf.Train() Not working in 'Example - FootBall detection.'

### ISSUE THREAD

**Issue by take2rohit** [Tessellate-Imaging/Monk_Object_Detection#15]
I was checking the code on Colab of Yolov3. The training isn't working. Please visit the link
[Colab Link](https://colab.research.google.com/github/Tessellate-Imaging/Monk_Object_Detection/blob/master/example_notebooks/7_yolov3/Example%20-%20FootBall%20detection.ipynb#scrollTo=vmdg7CrIlPIc)
Please look into the error. 
![image](https://user-images.githubusercontent.com/40535193/77235372-07238680-6bdb-11ea-87c6-356fb44236ef.png)

**Comment by abhi-kumar** [comment]
Thank you for pointing out the issue. Will test and rectify soon. If you have found a solution do let us know.

**Comment by THEFASHIONGEEK** [comment]
![image](https://user-images.githubusercontent.com/50513357/77244396-6fee1b80-6c3a-11ea-845e-6446de667507.png)
I didn't get any error.

**Comment by abhi-kumar** [comment]
@take2rohit can you try and reproduce the errors and mention the steps that lead to that error?

**Comment by take2rohit** [comment]
@THEFASHIONGEEK could you please share your Colab notebook link?

**Comment by THEFASHIONGEEK** [comment]
@take2rohit I stopped after one epoch because its time taking.
[Colab link](https://colab.research.google.com/drive/19uilwXz6ZMlH5ztiopOrQT9oZosJ8eCm)

**Comment by take2rohit** [comment]
> @take2rohit I stopped after one epoch because its time taking.
> [Colab link](https://colab.research.google.com/drive/19uilwXz6ZMlH5ztiopOrQT9oZosJ8eCm)

Thanks! @THEFASHIONGEEK. The code worked fine. IDK what went wrong in my implementation.
