### ISSUE TITLE
Suggestion: Colab notebook enhancements

### ISSUE THREAD

**Issue by take2rohit** [Tessellate-Imaging/Monk_Object_Detection#16]
There is a problem of paths in colab.
1. Colab doesnt know what is ```../../bar``` we need to rather specify ```Monk/foo/bar```
2. Instead of adding paths like ```relative + '\' + final + '\' ``` we should rather use ```os.path.join(relative,final)```. This is because sometimes it had thrown error even if i entered correct path (that slash caused problem)
3. Since most of the code base is based on tf 1.x its best to specify ```%tensorflow_version 1.x``` at starting of notebook (Since colab will make tf2 default very soon)

**Comment by abhi-kumar** [comment]
2) That's a good point. Using os.path.join is a better option than using a string to do the same.
Please make appropriate changes to notebooks and core code and raise multiple PRs. 

For the colab points, I will specify a few things soon.

**Comment by abhi-kumar** [comment]
Closing the Issue. Solution provided
