### ISSUE TITLE
Suggestion: Modify the documentation in example notebooks 

### ISSUE THREAD

**Issue by Het-Shah** [Tessellate-Imaging/Monk_Object_Detection#19]
In the pytorch example notebook, for the annotation format of train_labels.csv file, the name of columns is given as "Id" and "Labels". Upon keeping this as the column names for my CSV file I got an error for wrong column names. Upon looking at sample datasets I found that the actual names for the columns are supposed to be "ID" and "Label". Please rectify to avoid confusion.

**Comment by abhi-kumar** [comment]
Thank you for pointing it out. Can you please reformat the associated code so that the column names are dynamic and not restricted to "ID and Label" . You may use pandas library to do the same

**Comment by Het-Shah** [comment]
Ok sure will do it
