### ISSUE TITLE
Missing resnet-101 in gluon.

### ISSUE THREAD

**Issue by mihir135** [Tessellate-Imaging/Monk_Object_Detection#20]
Firstly, Thanks for this amazing repository.

As I was going through some of your code and documentaions, I realized that you have mentioned gluon supports SSD with resnet-101 in the documentation but it isn't present into the code itself.

Does it really support SSD with resnet-101?

Thanks and Regards.

**Comment by abhi-kumar** [comment]
Hi Mihir,

Thank you for pointing it out. SSD with Resnet-101 had errors so we commented it out. Will resolve this error soon.

**Comment by abhi-kumar** [comment]
The docs have been updated accordingly.
