### ISSUE TITLE
Update requirement.txt

### ISSUE THREAD

**Issue by mihir135** [Tessellate-Imaging/Monk_Object_Detection#21]
Hello Guyz,

You have strictly defined the version of pytorch which is 1.3.1, but not for torchvision. 
You should define the torchvision version(0.4.2) as well because torchvision (0.5.0 latest) is not compatible with torch==1.3.1.

**Comment by THEFASHIONGEEK** [comment]
Hi Mihir,

Can you please specify which object detection requirement.txt?

**Comment by mihir135** [comment]
Monk_Object_Detection/2_pytorch_finetune/installation/requirements.txt

Didn't checked other pytorch related requirement.txts.

**Comment by abhi-kumar** [comment]
@mihir135 the requirements have been updated. Please check now
