### ISSUE TITLE
Problem in training Retinanet

### ISSUE THREAD

**Issue by Midhilesh29** [Tessellate-Imaging/Monk_Object_Detection#29]
1. Is there any way to apply custom data augmentation?
2. Is there any way to save models in during training rather than waiting till the end of training?
3. Is there any way to resume the training?

**Comment by abhi-kumar** [comment]
All the mentioned features are development phase for every pipeline. Like monk classification, a project management system is missing here, hence resuming training is yet to be incorporated in the stable version

**Comment by abhi-kumar** [comment]
Mentioned features will be added soon.
