### ISSUE TITLE
Training RFBNET in colab, couldn't find '/content/coco_cache/Monk_Object_Detection/example_notebooks/sample_dataset_kangaroo_Images_gt_roidb.pkl'

### ISSUE THREAD

**Issue by annie7777** [Tessellate-Imaging/Monk_Object_Detection#31]
Hi Thanks for your nice work ! When I try to train rfbnet in colab. It gives me this error, it couldn't find the coco cache file
Monk_Object_Detection/8_pytorch_rfbnet/lib/data/coco.py in __init__(self, root_dir, coco_dir, set_dir, preproc, target_transform, dataset_name)

Monk_Object_Detection/8_pytorch_rfbnet/lib/data/coco.py in _load_coco_annotations(self, coco_name, indexes, _COCO)

FileNotFoundError: [Errno 2] No such file or directory: '/content/coco_cache/Monk_Object_Detection/example_notebooks/sample_dataset_kangaroo_Images_gt_roidb.pkl'

**Comment by abhi-kumar** [comment]
Thank you for pointing out the issue. Will resolve it very soon.

**Comment by annie7777** [comment]
Thanks for your reply very looking foward to your response. I found this is the same for the lcoal system as well

**Comment by abhi-kumar** [comment]
The issue has been resolved. Please check and confirm

**Comment by annie7777** [comment]
> The issue has been resolved. Please check and confirm

thanks!. It's working!
