### ISSUE TITLE
ModuleNotFoundError: No module named 'top_pool'

### ISSUE THREAD

**Issue by Sujith93** [Tessellate-Imaging/Monk_Object_Detection#32]
![image](https://user-images.githubusercontent.com/15892407/81194948-d8bb0880-8fda-11ea-9ac5-c5365ec19421.png)

**Comment by THEFASHIONGEEK** [comment]
I think, You may not install the MS COCO API.

**Comment by Sujith93** [comment]
Created a virtual environment and navigated to 6_cornernet_lite/installation and run
**./install.sh**

**Comment by THEFASHIONGEEK** [comment]
Install `git+https://github.com/abhi-kumar/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI`
 and if the error still persists please let us know.

**Comment by THEFASHIONGEEK** [comment]
after the environment is built, re-clone the project and recompile. 
If the issue still persists please let us know.

**Comment by Sujith93** [comment]
I installed git+https://github.com/abhi-kumar/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
Then 
![image](https://user-images.githubusercontent.com/15892407/81208453-b03c0a00-8fec-11ea-97b5-13b89883cf71.png)
Because the file created top_pool.cpython-36m-x86_64-linux-gnu.so has 0 kb
But after re-clone the project and recompile that file is created with nearly 5mb.
Then everything started working.

Thanks for your support
