### ISSUE TITLE
Error while training Hand_Segmentation model

### ISSUE THREAD

**Issue by Kushagra-awasthi** [Tessellate-Imaging/Monk_Object_Detection#39]
I have created a hand segmentation system using the example notebooks of the segmentation models but I am getting an Index Error. Please look into the error. I am attaching the Colab notebook link below.

[Colab Notebook](https://colab.research.google.com/drive/13bwzAzA69n_Xyjvpfw6-zuoTKAIPfv2Q?usp=sharing)
![image](https://user-images.githubusercontent.com/43932910/88585105-458cee80-d070-11ea-90b1-1b97dbdf5dde.png)

**Comment by abhi-kumar** [comment]
Is this issue resolved now?

**Comment by Kushagra-awasthi** [comment]
Yes sir, the issue is now resolved.

**Comment by abhi-kumar** [comment]
Closing the issue.
