### ISSUE TITLE
Error while loading  TRAIN-gluon-ssd_300_vgg16_atrous_coco

### ISSUE THREAD

**Issue by venkatchintha** [Tessellate-Imaging/Monk_Object_Detection#50]
Hello,

I got error while running this code

**gtf.Dataset(root, img_dir, anno_file, batch_size=batch_size);**

100%|██████████| 49281/49281 [00:01<00:00, 38741.31it/s]
100%|██████████| 49281/49281 [22:31<00:00, 36.46it/s]
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-21-26f6f75c1f0c> in <module>()
----> 1 gtf.Dataset(root, img_dir, anno_file, batch_size=batch_size);

8 frames
/content/Monk_Object_Detection/1_gluoncv_finetune/lib/detector_prototype.py in Dataset(self, root, img_dir, anno_file, batch_size, num_workers)
    148         os.system(cmd2);
    149 
--> 150         self.system_dict["local"]["train_dataset"] = gcv.data.RecordFileDetection('train.rec')
    151 
    152 

/usr/local/lib/python3.6/dist-packages/gluoncv/data/recordio/detection.py in __init__(self, filename, coord_normalized)
     64     """
     65     def __init__(self, filename, coord_normalized=True):
---> 66         super(RecordFileDetection, self).__init__(filename)
     67         self._coord_normalized = coord_normalized
     68 

/usr/local/lib/python3.6/dist-packages/mxnet/gluon/data/vision/datasets.py in __init__(self, filename, flag, transform)
    244     """
    245     def __init__(self, filename, flag=1, transform=None):
--> 246         super(ImageRecordDataset, self).__init__(filename)
    247         self._flag = flag
    248         self._transform = transform

/usr/local/lib/python3.6/dist-packages/mxnet/gluon/data/dataset.py in __init__(self, filename)
    182         self.idx_file = os.path.splitext(filename)[0] + '.idx'
    183         self.filename = filename
--> 184         self._record = recordio.MXIndexedRecordIO(self.idx_file, self.filename, 'r')
    185 
    186     def __getitem__(self, idx):

/usr/local/lib/python3.6/dist-packages/mxnet/recordio.py in __init__(self, idx_path, uri, flag, key_type)
    243         self.key_type = key_type
    244         self.fidx = None
--> 245         super(MXIndexedRecordIO, self).__init__(uri, flag)
    246 
    247     def open(self):

/usr/local/lib/python3.6/dist-packages/mxnet/recordio.py in __init__(self, uri, flag)
     69         self.pid = None
     70         self.is_open = False
---> 71         self.open()
     72 
     73     def open(self):

/usr/local/lib/python3.6/dist-packages/mxnet/recordio.py in open(self)
    246 
    247     def open(self):
--> 248         super(MXIndexedRecordIO, self).open()
    249         self.idx = {}
    250         self.keys = []

/usr/local/lib/python3.6/dist-packages/mxnet/recordio.py in open(self)
     77             self.writable = True
     78         elif self.flag == "r":
---> 79             check_call(_LIB.MXRecordIOReaderCreate(self.uri, ctypes.byref(self.handle)))
     80             self.writable = False
     81         else:

/usr/local/lib/python3.6/dist-packages/mxnet/base.py in check_call(ret)
    251     """
    252     if ret != 0:
--> 253         raise MXNetError(py_str(_LIB.MXGetLastError()))
    254 
    255 

MXNetError: [23:35:57] src/io/local_filesys.cc:209: Check failed: allow_null:  LocalFileSystem::Open "train.rec": No such file or directory
Stack trace:
  [bt] (0) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x2ea6de8) [0x7f1c7eef6de8]
  [bt] (1) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x2e9e9ba) [0x7f1c7eeee9ba]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(MXRecordIOReaderCreate+0x2d) [0x7f1c7e5772cd]
  [bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f1ccb1e1dae]
  [bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x22f) [0x7f1ccb1e171f]
  [bt] (5) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2b4) [0x7f1ccb3f55c4]
  [bt] (6) /usr/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x11c33) [0x7f1ccb3f5c33]
  [bt] (7) /usr/bin/python3(_PyObject_FastCallKeywords+0x19c) [0x5a9eec]
  [bt] (8) /usr/bin/python3() [0x50a783]

Link to code--https://github.com/venkatchintha/Project0/blob/master/Copy_of_TRAIN_gluon_ssd_300_vgg16_atrous_coco.ipynb

**Comment by abhi-kumar** [comment]
The issue is with data format. We will check your notebook and get back to you soon on this

**Comment by abhi-kumar** [comment]
The notebook on sample data is running fine, please check if the data provided to the training engine exists or not.
