### ISSUE TITLE
Error while converting from monk to COCO

### ISSUE THREAD

**Issue by venkatchintha** [Tessellate-Imaging/Monk_Object_Detection#51]
I am getting below error while running code. The same code i ran before it works fine. some times it doesn't give any error.  and some times it throws error.

  0%|          | 0/49281 [00:00<?, ?it/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-a4ddfb4cbaeb> in <module>()
     14     image_in_path = input_images_folder + "/" + img_name;
     15     img = cv2.imread(image_in_path, 1);
---> 16     h, w, c = img.shape;
     17 
     18     images_tmp = {};

AttributeError: 'NoneType' object has no attribute 'shape'

**Please see below same  code that converting monk to COCO**

https://github.com/venkatchintha/Project0/blob/master/Monk_to_COCO.ipynb

**Comment by abhi-kumar** [comment]
The image name or path maybe incorrect in the annotation of one or more files. This is an opencv error, if the image doesn't exist opencv doesn't raise an error while reading but reads it as Nonetype. Any further operation on it, like finding the shape raises an error

**Comment by venkatchintha** [comment]
Yes but i gave same path before and it works fine. When i ran code again it is giving me error. For same path it is working fine sometimes and giving error sometimes

**Comment by abhi-kumar** [comment]
The code samples through the data in sub-batches. In an epoch not all images may be used because of random sampling. Hence, whenever the wrong set of image is selected the error is raised. Could you please check all the annotation paths in the json file of coco.

**Comment by abhi-kumar** [comment]
Is this error resolved now?

**Comment by venkatchintha** [comment]
Yes, i have some mismatches between images and labels in csv. I cleaned those and converted to coco . Thank you

**Comment by abhi-kumar** [comment]
Closing the issue.
