### ISSUE TITLE
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sinchubhat** [Tessellate-Imaging/Monk_Object_Detection#63]
An error occurred during training 
The pipeline used is mxrcnn

![image](https://user-images.githubusercontent.com/32384381/91460966-156e8080-e8a6-11ea-9e9e-9a1c35cc888e.png)
![image](https://user-images.githubusercontent.com/32384381/91461023-25866000-e8a6-11ea-9aac-79d9e0ac0068.png)
![image](https://user-images.githubusercontent.com/32384381/91461081-37680300-e8a6-11ea-8f3e-7db69add629f.png)

**Comment by abhi-kumar** [comment]
Check cuda version by using command nvcc -V

And accordingly install mxnet, for cuda 10.1 mxnet-cu100
